INDUSTRY_ASSET_TURNOVER_RATIO_BENCHMARK = {
    "Technology": 1.2,
    "Healthcare": 0.8,
    "Finance": 0.6,
    "Consumer Discretionary": 1.5,
    "Energy": 0.5,
    "Materials": 1.0,
    "Utilities": 0.4,
    "Communication Services": 1.0,
    "Real Estate": 0.8,
    "Industrials": 1.2,
    "Automobile": 1.0,
    "Consumer Staples": 1.2,
    "Pharmaceuticals": 0.7,
    "IT Services": 1.5,
}

INDUSTRY_INVENTORY_TURNOVER_RATIO_BENCHMARK = {
    "Technology": 5.0,
    "Healthcare": 4.0,
    "Finance": 3.0,
    "Consumer Discretionary": 6.0,
    "Energy": 2.5,
    "Materials": 4.0,
    "Utilities": 3.0,
    "Communication Services": 5.0,
    "Real Estate": 3.5,
    "Industrials": 4.5,
    "Automobile": 6.5,
    "Consumer Staples": 4.0,
    "Pharmaceuticals": 3.5,
    "IT Services": 5.5,
}

INDUSTRY_RECEIVABLES_TURNOVER_RATIO_BENCHMARK = {
    "Technology": 5.5,
    "Healthcare": 4.5,
    "Finance": 6.0,
    "Consumer Discretionary": 8.0,
    "Energy": 4.0,
    "Materials": 6.5,
    "Utilities": 4.0,
    "Communication Services": 5.5,
    "Real Estate": 4.5,
    "Industrials": 6.0,
    "Automobile": 7.0,
    "Consumer Staples": 6.0,
    "Pharmaceuticals": 5.5,
    "IT Services": 6.5,
}
