INDUSTRY_ROA_BENCHMARK = {
    "Technology": 10.0,
    "Healthcare": 8.0,
    "Finance": 1.5,
    "Consumer Discretionary": 6.0,
    "Energy": 4.0,
    "Materials": 5.0,
    "Utilities": 5.0,
    "Communication Services": 8.0,
    "Real Estate": 5.0,
    "Industrials": 6.0,
    "Automobile": 3.0,
    "Consumer Staples": 7.0,
    "Pharmaceuticals": 12.0,
    "IT Services": 15.0,
}

INDUSTRY_ROE_BENCHMARK = {
    "Technology": 20.0,
    "Healthcare": 15.0,
    "Finance": 18.0,
    "Consumer Discretionary": 15.0,
    "Energy": 12.0,
    "Materials": 12.0,
    "Utilities": 8.0,
    "Communication Services": 18.0,
    "Real Estate": 12.0,
    "Industrials": 14.0,
    "Automobile": 10.0,
    "Consumer Staples": 16.0,
    "Pharmaceuticals": 25.0,
    "IT Services": 30.0,
}

INDUSTRY_PROFIT_MARGIN_BENCHMARK = {
    "Technology": 25.0,
    "Healthcare": 15.0,
    "Finance": 20.0,
    "Consumer Discretionary": 10.0,
    "Energy": 8.0,
    "Materials": 10.0,
    "Utilities": 10.0,
    "Communication Services": 20.0,
    "Real Estate": 15.0,
    "Industrials": 12.0,
    "Automobile": 5.0,
    "Consumer Staples": 15.0,
    "Pharmaceuticals": 30.0,
    "IT Services": 40.0,
}

INDUSTRY_GROSS_PROFIT_MARGIN_BENCHMARK = {
    "Technology": 60.0,
    "Healthcare": 50.0,
    "Finance": 50.0,
    "Consumer Discretionary": 40.0,
    "Energy": 25.0,
    "Materials": 30.0,
    "Utilities": 30.0,
    "Communication Services": 50.0,
    "Real Estate": 40.0,
    "Industrials": 35.0,
    "Automobile": 20.0,
    "Consumer Staples": 35.0,
    "Pharmaceuticals": 70.0,
    "IT Services": 80.0,
}

INDUSTRY_OPERATING_PROFIT_MARGIN_BENCHMARK = {
    "Technology": 30.0,
    "Healthcare": 25.0,
    "Finance": 20.0,
    "Consumer Discretionary": 15.0,
    "Energy": 10.0,
    "Materials": 12.0,
    "Utilities": 15.0,
    "Communication Services": 25.0,
    "Real Estate": 20.0,
    "Industrials": 18.0,
    "Automobile": 10.0,
    "Consumer Staples": 20.0,
    "Pharmaceuticals": 40.0,
    "IT Services": 45.0,
}
